const categories = [
    'Design and Creative',
    'Software Engineering',
    'Marketing and Sales',
    'Finance and Accounting',
    'Human Resources',
    'Operations and Management',
    'Customer Service',
    'Product Management',
    'Data Science and Analytics',
    'Information Technology',
    'Education and Training',
    'Healthcare',
    'Legal Services',
    'Manufacturing and Production',
    'Research and Development',
    'Administration and Support',
    'Project Management',
    'Cybersecurity',
    'UX/UI Design',
    'Web Development',
    'Mobile Development',
    'Game Development',
    'Social Media Management',
    'Content Creation',
    'E-commerce',
    'Consulting',
    'Supply Chain Management',
    'Telecommunications',
    'Real Estate',
    'Nonprofit and Community Services'
  ];
  
  export default categories;